# Stage 1: Build the application
FROM node:20-alpine AS build

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package*.json ./

# Install production dependencies
RUN npm ci --only=production

# Copy the application code to the working directory
COPY . .

# Stage 2: Run the application
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy dependencies and build from the previous stage
COPY --from=build /app /app

# Expose the port the app runs on
EXPOSE 5000

# Define environment variables (add your own if needed)
ENV NODE_ENV=production


ARG MODE
ARG APP_URL
ARG NODE_ENV
ARG DB_HOST
ARG DB_NAME
ARG DB_USER
ARG DB_PASS
ARG DB_PORT
ARG APP_EMAIL
ARG STRIPE_SECRET_KEY
ARG STRIPE_PUBLISH_KEY
ARG ELASTIC_EMAIL_API_KEY
ARG CLOUDINARY_USERNAME
ARG CLOUDINARY_API_KEY
ARG CLOUDINARY_API_SECRET_KEY
ARG SENDGRID_API_KEY
ARG SUPPORT_EMAIL
ARG NO_REPLY_EMAIL
ARG FLUTTERWAVE_PUBLIC_TEST_KEY
ARG FLUTTERWAVE_SECRET_TEST_KEY
ARG FLUTTERWAVE_ENCRYPTION_KEY
ARG FLUTTERWAVE_SECRET_HASH
ARG FLUTTERWAVE_PUBLIC_LIVE_KEY
ARG FLUTTERWAVE_SECRET_LIVE_KEY


ENV MODE=$MODE
ENV APP_URL=$APP_URL
ENV NODE_ENV=$NODE_ENV
ENV DB_NAME=$DB_NAME
ENV DB_USER=$DB_USER
ENV DB_PASS=$DB_PASS
ENV DB_HOST=$DB_HOST
ENV DB_PORT=$DB_PORT
ENV APP_EMAIL=$APP_EMAIL
ENV STRIPE_SECRET_KEY=$STRIPE_SECRET_KEY
ENV STRIPE_PUBLISH_KEY=$STRIPE_PUBLISH_KEY
ENV ELASTIC_EMAIL_API_KEY=$ELASTIC_EMAIL_API_KEY
ENV CLOUDINARY_USERNAME=$CLOUDINARY_USERNAME
ENV CLOUDINARY_API_KEY=$CLOUDINARY_API_KEY
ENV CLOUDINARY_API_SECRET_KEY=$CLOUDINARY_API_SECRET_KEY
ENV SENDGRID_API_KEY=$SENDGRID_API_KEY
ENV SUPPORT_EMAIL=$SUPPORT_EMAIL
ENV NO_REPLY_EMAIL=$NO_REPLY_EMAIL
ENV FLUTTERWAVE_PUBLIC_TEST_KEY=$FLUTTERWAVE_PUBLIC_TEST_KEY
ENV FLUTTERWAVE_SECRET_TEST_KEY=$FLUTTERWAVE_SECRET_TEST_KEY
ENV FLUTTERWAVE_ENCRYPTION_KEY=$FLUTTERWAVE_ENCRYPTION_KEY
ENV FLUTTERWAVE_SECRET_HASH=$FLUTTERWAVE_SECRET_HASH
ENV FLUTTERWAVE_PUBLIC_LIVE_KEY=$FLUTTERWAVE_PUBLIC_LIVE_KEY
ENV FLUTTERWAVE_SECRET_LIVE_KEY=$FLUTTERWAVE_SECRET_LIVE_KEY

# Define the command to run your application (runs migrations first)
CMD ["npm", "start"]
